name: iOS starter workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Export IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          # Get the list of schemes from the project
          scheme_list=$(xcodebuild -list -json | tr -d "\n")

          # Extract the scheme name (assuming the first target is the default)
          scheme=$(echo $scheme_list | ruby -e "require 'json'; schemes = JSON.parse(STDIN.gets)['project']['targets']; puts schemes.first['name']")

          # Output the detected scheme
          echo "Using default scheme: $scheme"

          # Save the scheme name to a file
          echo $scheme > scheme.txt

      - name: Archive iOS App
        run: |
          # Read the scheme from the file
          scheme=$(cat scheme.txt)

          # Determine if workspace or project file is present
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`

          # Archive the app to create an .xcarchive file
          xcodebuild -scheme "$scheme" -"$filetype_parameter" "$file_to_build" archive -archivePath $PWD/build/$scheme.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Export IPA
        run: |
          # Read the scheme from the file
          scheme=$(cat scheme.txt)

          # Export the IPA from the archive
          export_options_plist="ExportOptions.plist" # Create or configure your ExportOptions.plist file
          xcodebuild -exportArchive -archivePath $PWD/build/$scheme.xcarchive -exportPath $PWD/build -exportOptionsPlist $export_options_plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: $PWD/build/*.ipa
